# B 队：黄泉+千冶·刃+椒丘+砂金（无花火）

ruleset: fribbels_perfection_200
total_substat_rolls: 54
roll_quality: max
diminishing_returns: false
datamine_commit: "4ce30f69b32dc259ab9a8da3ba57035485103221"

characters:
  jiaoqiu:
    role: amp_support
    target_speed: 143
    err: 1.0
    light_cone: { id: 23029, superimposition: 1 }
    relic_sets:
      cavern: prisoner_116
      planar: pan_cosmic_303
    mains:
      head: hp_flat
      hands: atk_flat
      body: ehr
      feet: speed
      sphere: fire_dmg
      rope: atk_pct

  mortenaxblade:
    role: hp_dps
    target_speed: 160
    err: 1.0
    light_cone: { id: 23059, superimposition: 1 }
    relic_sets:
      cavern: pioneer_117
      planar: izumo_314
    mains:
      head: hp_flat
      hands: atk_flat
      body: crit_rate
      feet: speed
      sphere: fire_dmg
      rope: hp_pct

  acheron:
    role: main_dps
    target_speed: 134
    err: 1.0
    light_cone: { id: 23024, superimposition: 1 }
    relic_sets:
      cavern: pioneer_117
      planar: izumo_314
    mains:
      head: hp_flat
      hands: atk_flat
      body: crit_rate
      feet: speed
      sphere: lightning_dmg
      rope: atk_pct

  aventurine:
    role: shielder
    target_speed: 134
    err: 1.0
    light_cone: { id: 23023, superimposition: 1 }
    relic_sets:
      cavern: knight_103
      planar: broken_keel_310
    mains:
      head: hp_flat
      hands: atk_flat
      body: def_pct
      feet: speed
      sphere: imaginary_dmg
      rope: def_pct
